name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          cd backend
          docker build -t your-backend-image .

      - name: Deploy to Heroku
        run: |
          docker tag your-backend-image registry.heroku.com/your-app-name/web
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
          docker push registry.heroku.com/your-app-name/web
          heroku container:release web -a your-app-name
